openapi: '3.0.2'
info:
  title: GORM MVC API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
    description: Example Mock Server
  - url: http://localhost:4010
    description: Local Mock Server by Prism
paths:
  /users:
    get:
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object 
                  properties:
                    id:
                      type: string
                      example: abd121e8-dumm-dumm-dumm-dummycreated
                    name:
                      type: string
                      example: Yehezkiel Saragih
                    email:
                      type: string
                      example: yehezkielsr@example.com
        '400':
          description: Request Failed
        '500':
          description: Server Error
    post:
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required: 
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User Created
        '400':
          description: Request Failed
        '500':
          description: Server Error
  /users/:id:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: string
                    example: abd121e8-dumm-dumm-dumm-dummycreated
                  name:
                    type: string
                    example: Yehezkiel Saragih
                  email:
                    type: string
                    example: yehezkielsr@example.com
        '400':
          description: Request Failed
        '404':
          description: Data Not Found
        '500':
          description: Server Error
    put:
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '204':
          description: Data Updated
        '400':
          description: Request Failed
        '404':
          description: Data Not Found
        '500':
          description: Server Error
    delete:
      responses:
        '204':
          description: Data Updated
        '400':
          description: Request Failed
        '404':
          description: Data Not Found
        '500':
          description: Server Error
  /books:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: bdd511ea-dumm-dumm-dumm-dummycreated
                    title:
                      type: string
                      example: Kalkulus Edisi 9, Jilid 1
                    author:
                      type: string
                      example: 'Dale Varberg; Edwin J. Purcell; Steven E. Rigdon'
                    publisher:
                      type: string
                      example: 'Penerbit Erlangga'
                    isbn:
                      type: string
                      example: '9789790339378'
                    language:
                      type: string
                      example: 'indonesian'
        '500':
          description: Server Error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - authors
                - publisher
                - language
              properties:
                title:
                  type: string
                author:
                  type: string
                  example: 'Dale Varberg; Edwin J. Purcell; Steven E. Rigdon'
                publisher:
                  type: string
                isbn:
                  type: string
                language:
                  type: string
      responses:
        '201':
          description: Book Created
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /books/:id:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: bdd511ea-dumm-dumm-dumm-dummycreated
                  title:
                    type: string
                    example: Kalkulus Edisi 9, Jilid 1
                  author:
                    type: string
                    example: 'Dale Varberg; Edwin J. Purcell; Steven E. Rigdon'
                  publisher:
                    type: string
                    example: 'Penerbit Erlangga'
                  isbn:
                    type: string
                    example: '9789790339378'
                  language:
                    type: string
                    example: 'indonesian'
        '404':
          description: Data Not Found
        '500':
          description: Server Error
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - authors
                - publisher
                - language
              properties:
                title:
                  type: string
                author:
                  type: string
                  example: 'Dale Varberg; Edwin J. Purcell; Steven E. Rigdon'
                publisher:
                  type: string
                isbn:
                  type: string
                language:
                  type: string
      responses:
        '204':
          description: Data Updated
        '400':
          description: Request Failed
        '404':
          description: Data Not Found
        '500':
          description: Server Error
    delete:
      responses:
        '204':
          description: Data Updated
        '400':
          description: Request Failed
        '404':
          description: Data Not Found
        '500':
          description: Server Error
